name: Save Docker Image

on:
  workflow_dispatch:  # 手动触发

jobs:
  save-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # 省略登录到 Docker Hub 的步骤

    - name: Pull Docker image
      run: docker pull mayanghua/instock

    - name: Save Docker image to file
      run: docker save -o mayanghua_instock.tar mayanghua/instock

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: mayanghua_instock
        path: mayanghua_instock.tar
